### ISSUE TITLE
Meten mogelijk met dit apparaat komt nog steeds soms op rood

### ISSUE THREAD

**Issue by Valcking** [Valcking/MobileProfileAndroid#4]

**Comment by JonasVinck** [comment]
was da toevallig na opnieuw in e loggen?

**Comment by Valcking** [comment]
Ja da kan zijn ja. Met dat ik er vaak werd uitgesmeten enzo

**Comment by JonasVinck** [comment]
tzou dan kunnen da da is omda die waarde gereset werd, ma ge moest ni hercalibreren?
